/*
# Seed Data — Living Zimbabwe Heritage Platform

## Overview
Populates all tables with realistic Zimbabwean cultural heritage demonstration data.
Content is clearly marked as demonstration/sample where factual sourcing has not
been established. No fabricated historical claims are presented as verified facts.

## Data Inserted
1. Places: Great Zimbabwe, Victoria Falls, Matobo Hills, Lake Kariba, Nyanga, Harare, Bulawayo, Masvingo, Mutare, Kwekwe
2. People: Mbuya Nehanda, Thomas Baines, contemporary creators
3. Stories: Traditional farming, rainmaking traditions, Great Zimbabwe, Tonga oral traditions, contemporary art, mbira music, etc.
4. Collections: Great Zimbabwe Collection, Traditional Farming, Contemporary Art, Traditional Music, etc.
5. Creators: Artists, musicians, craftspeople with portfolios
6. Educational Resources: Grade 4-7 lessons across Heritage Studies, History, Geography, Agriculture
7. Quizzes: Linked to educational resources with questions and answers
8. Submissions: A sample community submission in the review queue
9. Verification Records: Audit trail for the sample submission

## Important Notes
1. All image URLs use Pexels stock photography as placeholders
2. Stories cover HERITAGE, EDUCATION, COMMUNITY, CREATORS, and CURRENT CULTURE categories
3. Educational resources link to stories, demonstrating the "one knowledge object, many uses" principle
4. Quizzes link to educational resources, completing the learning loop
*/

-- ============================================================
-- PLACES
-- ============================================================
INSERT INTO places (name, slug, description, province, district, latitude, longitude, category, historical_period, image_url, featured) VALUES
('Great Zimbabwe', 'great-zimbabwe', 'The ruins of a medieval city near Masvingo, built between the 11th and 15th centuries. A UNESCO World Heritage Site and the namesake of the nation.', 'Masvingo', 'Masvingo', -20.2667, 30.9333, 'heritage', 'Medieval (11th–15th century)', 'https://images.pexels.com/photos/131736/pexels-photo-131736.jpeg?auto=compress&cs=tinysrgb&w=800', true),
('Victoria Falls', 'victoria-falls', 'Known locally as Mosi-oa-Tunya ("The Smoke That Thunders"), one of the largest waterfalls in the world on the Zambezi River.', 'Matabeleland North', 'Hwange', -17.9243, 25.8572, 'natural', 'Natural landmark', 'https://images.pexels.com/photos/206355/pexels-photo-206355.jpeg?auto=compress&cs=tinysrgb&w=800', true),
('Matobo Hills', 'matobo-hills', 'A UNESCO World Heritage Site of granite rock formations, San rock art dating back 13,000 years, and sacred sites for the Mwari religion.', 'Matabeleland South', 'Matobo', -20.5500, 28.4833, 'heritage', 'Ancient to present', 'https://images.pexels.com/photos/159138/pexels-photo-159138.jpeg?auto=compress&cs=tinysrgb&w=800', true),
('Lake Kariba', 'lake-kariba', 'One of the world''s largest artificial lakes, created in 1959 by damming the Zambezi River. Home to the Tonga people who were relocated.', 'Mashonaland West', 'Kariba', -16.5167, 28.8667, 'natural', 'Modern (1959–present)', 'https://images.pexels.com/photos/1654748/pexels-photo-1654748.jpeg?auto=compress&cs=tinysrgb&w=800', false),
('Nyanga', 'nyanga', 'A mountainous area in eastern Zimbabwe with ancient stone ruins, terraced fields, and the Ziwa archaeological site.', 'Manicaland', 'Nyanga', -18.4333, 32.7500, 'heritage', 'Ancient', 'https://images.pexels.com/photos/14938680/pexels-photo-14938680.jpeg?auto=compress&cs=tinysrgb&w=800', false),
('Harare', 'harare', 'The capital and largest city of Zimbabwe, founded in 1890 as Salisbury. A center of contemporary culture, art, and commerce.', 'Harare', 'Harare', -17.8252, 31.0335, 'urban', 'Modern', 'https://images.pexels.com/photos/614117/pexels-photo-614117.jpeg?auto=compress&cs=tinysrgb&w=800', true),
('Bulawayo', 'bulawayo', 'The second-largest city, known as the "City of Kings." A major center for Ndebele culture, arts, and history.', 'Bulawayo', 'Bulawayo', -20.1500, 28.5833, 'urban', 'Modern', 'https://images.pexels.com/photos/2859169/pexels-photo-2859169.jpeg?auto=compress&cs=tinysrgb&w=800', true),
('Masvingo', 'masvingo-town', 'A town in southeastern Zimbabwe, the closest urban center to Great Zimbabwe. Formerly known as Fort Victoria.', 'Masvingo', 'Masvingo', -20.0747, 30.8333, 'urban', 'Modern', 'https://images.pexels.com/photos/2078805/pexels-photo-2078805.jpeg?auto=compress&cs=tinysrgb&w=800', false),
('Eastern Highlands', 'eastern-highlands', 'A range of mountains along the Zimbabwe-Mozambique border, home to mist forests, waterfalls, and diverse ecosystems.', 'Manicaland', 'Mutare', -18.5000, 32.6000, 'natural', 'Natural landmark', 'https://images.pexels.com/photos/14938680/pexels-photo-14938680.jpeg?auto=compress&cs=tinysrgb&w=800', false),
('Hwange', 'hwnage', 'Hwange National Park is the largest game reserve in Zimbabwe, home to one of Africa''s largest elephant populations.', 'Matabeleland North', 'Hwange', -19.0000, 26.5000, 'natural', 'Modern', 'https://images.pexels.com/photos/2223865/pexels-photo-2223865.jpeg?auto=compress&cs=tinysrgb&w=800', false)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- PEOPLE
-- ============================================================
INSERT INTO people (name, slug, bio, role, community, province, image_url, birth_year, death_year, featured) VALUES
('Mbuya Nehanda Charwe Nyakasikana', 'mbuya-nehanda', 'A Shona spirit medium who led resistance against British colonisation in the 1890s. Her legacy is central to Zimbabwean identity and the independence movement. [Demonstration content — sourced from public historical accounts]', 'Spirit Medium / Resistance Leader', 'Shona', 'Mashonaland Central', 'https://images.pexels.com/photos/3752854/pexels-photo-3752854.jpeg?auto=compress&cs=tinysrgb&w=400', 1862, 1898, true),
('Thomas Mapfumo', 'thomas-mapfumo', 'Known as "The Lion of Zimbabwe," a musician who developed chimurenga music, blending traditional Shona mbira music with modern instruments. His music became the soundtrack of the independence struggle.', 'Musician', 'Shona', 'Harare', 'https://images.pexels.com/photos/167636/pexels-photo-167636.jpeg?auto=compress&cs=tinysrgb&w=400', 1945, NULL, true),
('Oliver Mtukudzi', 'oliver-mtukudzi', 'A legendary Zimbabwean musician, songwriter, and philanthropist known for his distinctive husky voice and blend of traditional and modern sounds. [Demonstration content]', 'Musician', 'Shona', 'Harare', 'https://images.pexels.com/photos/1538343/pexels-photo-1538343.jpeg?auto=compress&cs=tinysrgb&w=400', 1952, 2019, true),
('Dominic Benhura', 'dominic-benhura', 'A renowned Zimbabwean sculptor known for his dynamic stone sculptures that capture movement and emotion. Part of the Shona sculpture movement.', 'Sculptor', 'Shona', 'Harare', 'https://images.pexels.com/photos/1145720/pexels-photo-1145720.jpeg?auto=compress&cs=tinysrgb&w=400', 1968, NULL, false)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- STORIES
-- ============================================================
INSERT INTO stories (title, slug, summary, content, content_type, category, language, community, historical_period, place_id, person_id, image_url, audio_url, verification_status, visibility, interviewee, interviewer, topics, sources, featured) VALUES
('The Stone City of Great Zimbabwe', 'great-zimbabwe-story', 'The Great Zimbabwe ruins are the largest ancient stone structures south of the Sahara. Built between the 11th and 15th centuries, they were the centre of the Kingdom of Zimbabwe, a powerful trading empire.', 'Great Zimbabwe stands as one of Africa''s most remarkable architectural achievements. The city was built entirely without mortar — dry-stone walls, some standing 11 metres high, constructed from granite blocks split from the surrounding hills.\n\nThe city was divided into the Hill Complex (the oldest section, likely a royal residence), the Great Enclosure (the largest single ancient structure in sub-Saharan Africa), and the Valley Ruins. At its peak, Great Zimbabwe may have housed up to 18,000 people.\n\nThe kingdom traded gold, ivory, and copper with merchants from as far as China — porcelain fragments and glass beads from Asia have been found at the site. The famous Zimbabwe Bird sculptures, carved from soapstone, became the national symbol of modern Zimbabwe.\n\nThe city was abandoned around 1450, possibly due to environmental pressure, trade route shifts, or political instability. The legacy of Great Zimbabwe — a monument to African engineering, trade, and civilisation — was reclaimed as the foundation of modern Zimbabwean national identity.', 'story', 'heritage', 'English', 'Shona', 'Medieval (11th–15th century)', (SELECT id FROM places WHERE slug='great-zimbabwe'), NULL, 'https://images.pexels.com/photos/131736/pexels-photo-131736.jpeg?auto=compress&cs=tinysrgb&w=800', NULL, 'published', 'public', NULL, NULL, ARRAY['Great Zimbabwe', 'architecture', 'trade', 'medieval', 'Kingdom of Zimbabwe', 'UNESCO'], 'Public historical records; UNESCO World Heritage Site documentation', true),

('Traditional Farming Practices of the Shona', 'traditional-farming', 'Elders describe the indigenous farming systems that sustained communities for centuries — crop rotation, intercropping, and spiritual connections to the land.', 'Traditional Shona farming was deeply connected to the cycles of nature and the spiritual world. Agriculture was not merely economic but cultural and spiritual.\n\nKey practices included:\n\n• Intercropping: maize, sorghum, millet, and groundnuts grown together to maximise land use and reduce pest vulnerability\n• Crop rotation: fields were rested and rotated to preserve soil fertility\n• Terracing: in hilly areas like Nyanga, ancient terraces prevented erosion\n• Seed saving: communities maintained diverse seed varieties adapted to local conditions\n• Rainmaking ceremonies: the Mukwerera ritual was performed to ask ancestors and Mwari for rain\n\nThe agricultural calendar was guided by observation of natural signs — the flowering of certain trees, the movement of birds, and the phases of the moon. Elders held detailed ecological knowledge passed down through generations.\n\nThis knowledge is increasingly relevant today as climate change threatens food security, and there is growing recognition that traditional practices offer sustainable, climate-resilient approaches. [Demonstration content — based on general ethnographic knowledge]', 'oral_history', 'heritage', 'English', 'Shona', 'Pre-colonial to present', (SELECT id FROM places WHERE slug='masvingo-town'), NULL, 'https://images.pexels.com/photos/2933243/pexels-photo-2933243.jpeg?auto=compress&cs=tinysrgb&w=800', NULL, 'published', 'public', 'Gogo Rumbidzai', 'Community interviewer', ARRAY['farming', 'agriculture', 'Shona', 'traditional', 'sustainable', 'rainmaking'], 'Community oral history; ethnographic literature', true),

('Rainmaking Traditions and the Mukwerera Ceremony', 'rainmaking-traditions', 'The Mukwerera ceremony is a traditional Shona rainmaking ritual that connects communities to their ancestors and the spirit world, asking for good rains and harvest.', 'Rainmaking ceremonies are among the most significant traditional spiritual practices in Zimbabwe. The Mukwerera ceremony, performed before the planting season, involves community gatherings led by a svikiro (spirit medium) who communicates with ancestors.\n\nThe ceremony typically includes:\n\n• Preparation of sacred spaces near rivers or mountains\n• Brewing of traditional beer (doro) as an offering\n• Music with mbira and hosho, which are believed to attract spirits\n• Divination to determine the right time for planting\n• Community feasting and celebration\n\nThese traditions reflect a worldview in which humans, ancestors, and the natural world are deeply interconnected. The ceremonies also served practical purposes — they synchronised planting times across communities and reinforced social bonds.\n\nIn contemporary Zimbabwe, some churches have incorporated elements of rainmaking prayer, while traditionalists continue the old practices. Climate change has added new urgency to these ceremonies, as communities seek spiritual and communal strength to face increasingly unpredictable rainfall.\n\n[Demonstration content — based on general ethnographic knowledge of Shona traditions]', 'oral_history', 'heritage', 'Shona', 'Shona', 'Pre-colonial to present', (SELECT id FROM places WHERE slug='masvingo-town'), (SELECT id FROM people WHERE slug='mbuya-nehanda'), 'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800', NULL, 'published', 'public', 'Sekuru Chigamba', 'Tendai Moyo', ARRAY['rainmaking', 'Mukwerera', 'ceremony', 'Shona', 'spiritual', 'mbira', 'ancestors'], 'Community oral history', true),

('Tonga Oral Traditions of the Zambezi', 'tonga-oral-traditions', 'The Tonga people have lived along the Zambezi for centuries. Their oral traditions preserve knowledge of the river, the land, and the displacement caused by the Kariba Dam.', 'The Tonga people (Batonga) have inhabited the Zambezi Valley for centuries, living as farmers, fishermen, and cattle herders. Their rich oral tradition includes stories of Nyaminyami — the river god — and songs that map the river''s moods and seasons.\n\nWhen the Kariba Dam was built in the 1950s, some 57,000 Tonga people were displaced from their ancestral lands. The flooding of the valley submerged graves, sacred sites, and homes. Operation Noah rescued thousands of animals from the rising waters, but the human cost was profound.\n\nTonga oral traditions record this displacement and the ongoing connection to the lands now beneath the lake. Stories speak of the spirits that still inhabit the waters, and the promise of Nyaminyami that one day the dam will break and the Tonga will return home.\n\nContemporary Tonga communities continue to preserve their language and culture through music — the ngoma drumming tradition — and through annual festivals. The Siachiliba Festival celebrates Tonga culture and heritage.\n\n[Demonstration content — based on general ethnographic accounts of Tonga culture]', 'oral_history', 'community', 'Tonga', 'Tonga', 'Pre-colonial to present', (SELECT id FROM places WHERE slug='lake-kariba'), NULL, 'https://images.pexels.com/photos/1654748/pexels-photo-1654748.jpeg?auto=compress&cs=tinysrgb&w=800', NULL, 'published', 'public', 'Chief Siachiliba', 'Community researcher', ARRAY['Tonga', 'Zambezi', 'Kariba', 'Nyaminyami', 'displacement', 'oral tradition'], 'Community oral history; Tonga cultural documentation', true),

('The Mbira: Sound of the Ancestors', 'mbira-music', 'The mbira dzavadzimu is a traditional Shona instrument that has been played for over a thousand years. Its music is believed to communicate with ancestors and is central to the Bira ceremony.', 'The mbira dzavadzimu ("mbira of the ancestors") is a lamellophone — a type of thumb piano — with 22 to 28 metal keys mounted on a hardwood soundboard (deze). It is often placed inside a large calabash gourd (deze) that amplifies and enriches the sound.\n\nMbira music has been central to Shona spiritual life for centuries. During the Bira ceremony, mbira is played continuously from sunset to sunrise, its hypnotic patterns believed to attract spirits who possess the medium and communicate with the community.\n\nThe music is cyclical, with multiple interlocking patterns creating a rich texture. Two or three players perform together, each playing slightly different parts. The resulting polyphony creates "inner melodies" — notes that are not physically played but are heard by listeners as the patterns interweave.\n\nIn the 20th century, mbira music was brought to wider audiences by musicians like Thomas Mapfumo, who adapted mbira patterns to electric guitar in his chimurenga style. Today, mbira is taught in schools, performed at concerts, and continues to evolve.\n\nContemporary artists are experimenting with mbira in jazz, electronic, and fusion contexts, ensuring this ancient instrument remains a living tradition.\n\n[Demonstration content — based on ethnomusicological literature]', 'music', 'creators', 'English', 'Shona', 'Ancient to present', (SELECT id FROM places WHERE slug='harare'), (SELECT id FROM people WHERE slug='thomas-mapfumo'), 'https://images.pexels.com/photos/167636/pexels-photo-167636.jpeg?auto=compress&cs=tinysrgb&w=800', NULL, 'published', 'public', NULL, NULL, ARRAY['mbira', 'music', 'Shona', 'Bira', 'ancestors', 'tradition', 'instruments'], 'Ethnomusicological literature; community knowledge', true),

('Contemporary Stone Sculpture Movement', 'stone-sculpture', 'The Zimbabwean stone sculpture movement emerged in the 1950s and has become one of Africa''s most celebrated art forms, with works displayed in museums worldwide.', 'The Shona sculpture movement began in 1957 when Frank McEwen, the first director of the National Gallery in Harare (then Salisbury), established a workshop school that encouraged local artists to work in stone. What emerged was unlike anything seen before.\n\nArtists worked primarily with local stones — serpentite, springstone, verdite, and soapstone — using techniques that seemed to release the form from within the rock. The sculptures drew on Shona mythology, family relationships, metamorphosis, and the spirit world.\n\nKey figures in the movement include:\n• Joram Mariga — often called the "father" of Shona sculpture\n• Henry Munyaradzi — known for his minimalist, geometric style\n• Dominic Benhura — famous for dynamic sculptures of children at play\n• Colleen Madamombe — celebrated for her depictions of women\n\nToday, the Tengenenge Sculpture Community near Guruve remains a vibrant center where sculptors live and work. Sculptures from Zimbabwe are found in the Museum of Modern Art in New York, the Rodin Museum in Paris, and collections worldwide.\n\nThe movement represents a powerful example of how traditional cultural themes can find expression in contemporary art forms, creating economic opportunities for artists while preserving and evolving cultural identity.\n\n[Demonstration content]', 'artwork', 'creators', 'English', 'Shona', 'Modern (1950s–present)', (SELECT id FROM places WHERE slug='harare'), (SELECT id FROM people WHERE slug='dominic-benhura'), 'https://images.pexels.com/photos/1145720/pexels-photo-1145720.jpeg?auto=compress&cs=tinysrgb&w=800', NULL, 'published', 'public', NULL, NULL, ARRAY['sculpture', 'stone', 'Shona art', 'contemporary', 'Tengenenge', 'art movement'], 'Art historical literature; gallery documentation', true),

('Youth Culture in Harare 2026', 'youth-culture-harare', 'A new generation of Zimbabwean artists, musicians, and creators are redefining what it means to be young and Zimbabwean in 2026.', 'Harare''s youth culture is vibrant and evolving. In neighborhoods like Mbare, Highfield, and Warren Park, young creators are building something new — a Zimbabwean identity that honours the past while embracing the future.\n\nMusic: The Amapiano and Afrobeats waves have merged with local sounds, creating a distinctly Zimbabwean urban music scene. Artists are rapping in Shona and Ndebele, addressing contemporary issues from unemployment to mental health.\n\nFashion: Young designers are blending traditional fabrics — like the chitenge — with streetwear silhouettes. Brands like Zuva are gaining continental recognition.\n\nArt: Street art murals in the CBD tell stories of historical figures and contemporary struggles. Collectives like Village Unhu are creating community art spaces.\n\nTechnology: Co-working spaces and tech hubs are emerging, with young developers building apps for local problems — from agriculture to transportation.\n\nThis is not a break from tradition but a continuation. The youth are the latest chapter in Zimbabwe''s living cultural story.\n\n[Contemporary demonstration content — reflecting general trends in Zimbabwean youth culture]', 'story', 'community', 'English', 'Shona/Ndebele', 'Contemporary (2020s)', (SELECT id FROM places WHERE slug='harare'), NULL, 'https://images.pexels.com/photos/2859169/pexels-photo-2859169.jpeg?auto=compress&cs=tinysrgb&w=800', NULL, 'published', 'public', NULL, NULL, ARRAY['youth', 'contemporary', 'Harare', 'culture', 'music', 'fashion', 'art'], 'Contemporary observation; cultural journalism', true),

('The Smoke That Thunders: Victoria Falls', 'victoria-falls-story', 'Known locally as Mosi-oa-Tunya, Victoria Falls is one of the most spectacular natural wonders on Earth, sacred to local communities for centuries.', 'Long before David Livingstone "discovered" it in 1855, the local Tonga and Lozi people knew the falls as Mosi-oa-Tunya — "The Smoke That Thunders." The falls were a sacred site, believed to be inhabited by powerful spirits.\n\nThe Zambezi River, nearly 1.7 kilometres wide at this point, plunges 108 metres into a narrow basalt gorge, creating a curtain of falling water and a permanent cloud of mist visible from 50 kilometres away. The roar can be heard from 40 kilometres distant.\n\nLocal traditions held that the falls were protected by the river god Nyaminyami, and that offerings should be made before approaching the most powerful sections. The falls were also a gathering place for trade and ceremony.\n\nToday, Victoria Falls is a UNESCO World Heritage Site shared between Zimbabwe and Zambia. It remains economically vital through tourism but faces challenges from climate change — in dry years, the falls can nearly run dry. Local communities continue to hold the site sacred, and there are ongoing discussions about how to balance tourism, conservation, and cultural respect.\n\n[Demonstration content — based on public documentation]', 'story', 'heritage', 'English', 'Tonga', 'Pre-colonial to present', (SELECT id FROM places WHERE slug='victoria-falls'), NULL, 'https://images.pexels.com/photos/206355/pexels-photo-206355.jpeg?auto=compress&cs=tinysrgb&w=800', NULL, 'published', 'public', NULL, NULL, ARRAY['Victoria Falls', 'Mosi-oa-Tunya', 'Zambezi', 'natural wonder', 'UNESCO', 'Nyaminyami'], 'Public documentation; UNESCO records', false),

('Women''s Heritage: Keepers of Knowledge', 'womens-heritage', 'Women in Zimbabwean communities have always been the primary transmitters of cultural knowledge — from oral histories to farming practices to craft traditions.', 'In Zimbabwean tradition, women have been the unsung custodians of cultural knowledge. Grandmothers (gogo / ambuya) are the storytellers, the historians, the teachers.\n\nWomen maintained:\n• Seed diversity — selecting and storing seeds for each planting season\n• Food preservation techniques — drying vegetables (mufushwa), fermenting, storage\n• Pottery traditions — making cooking pots, beer brewing vessels, water containers\n• Basket weaving — making storage containers and winnowing trays\n• Oral histories — telling tales (ngano) that taught values and preserved memory\n• Healing knowledge — herbal medicines for common ailments\n• Music and dance — many traditional dances originated with women\n\nDespite this, women''s cultural contributions have often been under-recognized in formal historical accounts. This platform seeks to change that by documenting and celebrating women''s heritage knowledge.\n\nContemporary women are also leading in new cultural spaces — as musicians, filmmakers, writers, and entrepreneurs. The story of Zimbabwean women is one of resilience, creativity, and the quiet power of keeping culture alive.\n\n[Demonstration content — based on general ethnographic knowledge]', 'story', 'community', 'English', 'Shona', 'Pre-colonial to present', NULL, (SELECT id FROM people WHERE slug='mbuya-nehanda'), 'https://images.pexels.com/photos/3752854/pexels-photo-3752854.jpeg?auto=compress&cs=tinysrgb&w=800', NULL, 'published', 'public', NULL, NULL, ARRAY['women', 'heritage', 'knowledge', 'tradition', 'seed saving', 'crafts'], 'Ethnographic literature; community knowledge', true)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- COLLECTIONS
-- ============================================================
INSERT INTO collections (name, slug, description, category, image_url, featured) VALUES
('Great Zimbabwe Collection', 'great-zimbabwe-collection', 'Stories, places, people, and educational resources connected to the Great Zimbabwe World Heritage Site.', 'heritage', 'https://images.pexels.com/photos/131736/pexels-photo-131736.jpeg?auto=compress&cs=tinysrgb&w=800', true),
('Traditional Farming Collection', 'traditional-farming-collection', 'Oral histories, practices, and knowledge about Zimbabwe''s indigenous agricultural systems.', 'heritage', 'https://images.pexels.com/photos/2933243/pexels-photo-2933243.jpeg?auto=compress&cs=tinysrgb&w=800', true),
('Zimbabwean Oral Histories', 'zimbabwean-oral-histories', 'A growing archive of community-contributed oral histories from across Zimbabwe.', 'community', 'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800', true),
('Contemporary Zimbabwean Art', 'contemporary-zimbabwean-art', 'Works and stories from Zimbabwe''s vibrant contemporary art scene — sculpture, painting, street art, and more.', 'creators', 'https://images.pexels.com/photos/1145720/pexels-photo-1145720.jpeg?auto=compress&cs=tinysrgb&w=800', true),
('Traditional Music', 'traditional-music-collection', 'The sounds of Zimbabwe — mbira, ngoma, chimurenga, and the evolution of musical traditions.', 'heritage', 'https://images.pexels.com/photos/167636/pexels-photo-167636.jpeg?auto=compress&cs=tinysrgb&w=800', false),
('Women''s Heritage Stories', 'womens-heritage-collection', 'Celebrating and documenting the cultural knowledge preserved and created by Zimbabwean women.', 'community', 'https://images.pexels.com/photos/3752854/pexels-photo-3752854.jpeg?auto=compress&cs=tinysrgb&w=800', true),
('Youth Culture 2026', 'youth-culture-2026', 'Documenting the culture being created by young Zimbabweans today — music, fashion, art, and innovation.', 'community', 'https://images.pexels.com/photos/2859169/pexels-photo-2859169.jpeg?auto=compress&cs=tinysrgb&w=800', false),
('Zimbabwean Crafts', 'zimbabwean-crafts', 'Basketry, pottery, woodcarving, stone sculpture, and the hands that create them.', 'creators', 'https://images.pexels.com/photos/4464036/pexels-photo-4464036.jpeg?auto=compress&cs=tinysrgb&w=800', false)
ON CONFLICT (slug) DO NOTHING;

-- Link stories to collections
INSERT INTO collection_items (collection_id, story_id, item_type, sort_order)
SELECT c.id, s.id, 'story', 1 FROM collections c, stories s WHERE c.slug='great-zimbabwe-collection' AND s.slug='great-zimbabwe-story'
ON CONFLICT DO NOTHING;
INSERT INTO collection_items (collection_id, story_id, item_type, sort_order)
SELECT c.id, s.id, 'story', 1 FROM collections c, stories s WHERE c.slug='traditional-farming-collection' AND s.slug='traditional-farming'
ON CONFLICT DO NOTHING;
INSERT INTO collection_items (collection_id, story_id, item_type, sort_order)
SELECT c.id, s.id, 'story', 1 FROM collections c, stories s WHERE c.slug='traditional-farming-collection' AND s.slug='rainmaking-traditions'
ON CONFLICT DO NOTHING;
INSERT INTO collection_items (collection_id, story_id, item_type, sort_order)
SELECT c.id, s.id, 'story', 1 FROM collections c, stories s WHERE c.slug='zimbabwean-oral-histories' AND s.slug='tonga-oral-traditions'
ON CONFLICT DO NOTHING;
INSERT INTO collection_items (collection_id, story_id, item_type, sort_order)
SELECT c.id, s.id, 'story', 1 FROM collections c, stories s WHERE c.slug='zimbabwean-oral-histories' AND s.slug='traditional-farming'
ON CONFLICT DO NOTHING;
INSERT INTO collection_items (collection_id, story_id, item_type, sort_order)
SELECT c.id, s.id, 'story', 1 FROM collections c, stories s WHERE c.slug='contemporary-zimbabwean-art' AND s.slug='stone-sculpture'
ON CONFLICT DO NOTHING;
INSERT INTO collection_items (collection_id, story_id, item_type, sort_order)
SELECT c.id, s.id, 'story', 1 FROM collections c, stories s WHERE c.slug='contemporary-zimbabwean-art' AND s.slug='youth-culture-harare'
ON CONFLICT DO NOTHING;
INSERT INTO collection_items (collection_id, story_id, item_type, sort_order)
SELECT c.id, s.id, 'story', 1 FROM collections c, stories s WHERE c.slug='traditional-music-collection' AND s.slug='mbira-music'
ON CONFLICT DO NOTHING;
INSERT INTO collection_items (collection_id, story_id, item_type, sort_order)
SELECT c.id, s.id, 'story', 1 FROM collections c, stories s WHERE c.slug='womens-heritage-collection' AND s.slug='womens-heritage'
ON CONFLICT DO NOTHING;
INSERT INTO collection_items (collection_id, story_id, item_type, sort_order)
SELECT c.id, s.id, 'story', 1 FROM collections c, stories s WHERE c.slug='youth-culture-2026' AND s.slug='youth-culture-harare'
ON CONFLICT DO NOTHING;

-- Link places to collections
INSERT INTO collection_items (collection_id, place_id, item_type, sort_order)
SELECT c.id, p.id, 'place', 2 FROM collections c, places p WHERE c.slug='great-zimbabwe-collection' AND p.slug='great-zimbabwe'
ON CONFLICT DO NOTHING;

-- ============================================================
-- CREATORS
-- ============================================================
INSERT INTO creators (name, slug, bio, category, skills, community, province, image_url, portfolio_images, story_id, featured) VALUES
('Tendai Mahachi', 'tendai-mahachi', 'A stone sculptor from Guruve who has been carving for 15 years. His work explores themes of family, transformation, and the connection between humans and animals.', 'Sculptor', ARRAY['Stone sculpture', 'Springstone carving', 'Serpentite'], 'Shona', 'Mashonaland Central', 'https://images.pexels.com/photos/1145720/pexels-photo-1145720.jpeg?auto=compress&cs=tinysrgb&w=400', ARRAY['https://images.pexels.com/photos/1145720/pexels-photo-1145720.jpeg?auto=compress&cs=tinysrgb&w=400', 'https://images.pexels.com/photos/3270223/pexels-photo-3270223.jpeg?auto=compress&cs=tinysrgb&w=400'], (SELECT id FROM stories WHERE slug='stone-sculpture'), true),
('Rumbi Katsande', 'rumbi-katsande', 'A mbira player and teacher from Harare. She runs workshops for young people, keeping the mbira tradition alive while experimenting with fusion sounds.', 'Musician', ARRAY['Mbira', 'Hosho', 'Vocals', 'Teaching'], 'Shona', 'Harare', 'https://images.pexels.com/photos/167636/pexels-photo-167636.jpeg?auto=compress&cs=tinysrgb&w=400', ARRAY['https://images.pexels.com/photos/167636/pexels-photo-167636.jpeg?auto=compress&cs=tinysrgb&w=400'], (SELECT id FROM stories WHERE slug='mbira-music'), true),
('Nompumelelo Sibanda', 'nompumelelo-sibanda', 'A basket weaver from Bulawayo who creates intricate pieces using traditional Ndebele weaving techniques with contemporary designs.', 'Craftsperson', ARRAY['Basket weaving', 'Grass craft', 'Beadwork'], 'Ndebele', 'Bulawayo', 'https://images.pexels.com/photos/4464036/pexels-photo-4464036.jpeg?auto=compress&cs=tinysrgb&w=400', ARRAY['https://images.pexels.com/photos/4464036/pexels-photo-4464036.jpeg?auto=compress&cs=tinysrgb&w=400'], NULL, false),
('Tafadzwa Chirwa', 'tafadzwa-chirwa', 'A photographer documenting contemporary Zimbabwean life — street scenes, cultural events, and the everyday beauty of Harare.', 'Photographer', ARRAY['Photography', 'Documentary', 'Street photography'], 'Shona', 'Harare', 'https://images.pexels.com/photos/1264210/pexels-photo-1264210.jpeg?auto=compress&cs=tinysrgb&w=400', ARRAY['https://images.pexels.com/photos/1264210/pexels-photo-1264210.jpeg?auto=compress&cs=tinysrgb&w=400', 'https://images.pexels.com/photos/2859169/pexels-photo-2859169.jpeg?auto=compress&cs=tinysrgb&w=400'], (SELECT id FROM stories WHERE slug='youth-culture-harare'), false),
('Sekuru Chigamba', 'sekuru-chigamba', 'An elder and traditional healer from Masvingo who holds deep knowledge of Shona spiritual practices, rainmaking traditions, and medicinal plants.', 'Cultural Practitioner', ARRAY['Traditional healing', 'Rainmaking ceremonies', 'Herbal medicine', 'Storytelling'], 'Shona', 'Masvingo', 'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=400', ARRAY['https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=400'], (SELECT id FROM stories WHERE slug='rainmaking-traditions'), false)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- EDUCATIONAL_RESOURCES
-- ============================================================
INSERT INTO educational_resources (title, slug, description, subject, grade, topic, curriculum_objective, learning_outcomes, difficulty, language, estimated_duration, resource_type, content, story_id, image_url, featured) VALUES
('Great Zimbabwe: The Stone City', 'great-zimbabwe-lesson', 'Discover the history and significance of Great Zimbabwe, one of Africa''s greatest medieval civilizations.', 'Heritage Studies', 'Grade 6', 'Great Zimbabwe', 'Understand the historical and cultural significance of Great Zimbabwe as a centre of trade, architecture, and political power.', 'By the end of this lesson, learners will be able to:\n1. Describe the location and structure of Great Zimbabwe\n2. Explain the economic activities of the Kingdom of Zimbabwe\n3. Identify the cultural significance of the Zimbabwe Bird\n4. Discuss why Great Zimbabwe is important to national identity', 'intermediate', 'English', '45 minutes', 'lesson', '## Introduction\nGreat Zimbabwe is one of the most important archaeological sites in Africa. Built between the 11th and 15th centuries, it was the capital of the Kingdom of Zimbabwe — a powerful trading empire.\n\n## The Architecture\nThe city was built using dry-stone construction — granite blocks fitted together without mortar. The walls, some up to 11 metres high, demonstrate remarkable engineering skill.\n\nKey areas:\n- **Hill Complex** — the oldest section, believed to be the royal residence\n- **Great Enclosure** — the largest single ancient structure in sub-Saharan Africa\n- **Valley Ruins** — residential areas\n\n## Trade and Economy\nGreat Zimbabwe was a trading centre. Gold, ivory, and copper were traded for goods from as far as China. Archaeologists have found Chinese porcelain and glass beads at the site.\n\n## The Zimbabwe Bird\nSoapstone bird sculptures were found at Great Zimbabwe. These birds became the national symbol of modern Zimbabwe, representing the connection between the ancient civilisation and the modern nation.\n\n## Why It Matters\nGreat Zimbabwe proves that African civilisations built complex, prosperous societies long before European contact. The name "Zimbabwe" comes from the Shona phrase "dzimba dza mabwe" meaning "houses of stone."\n\n## Discussion Questions\n1. Why do you think the builders used stone instead of other materials?\n2. What does the trade with China tell us about Great Zimbabwe''s connections?\n3. Why is it important that the modern country is named after this ancient city?', (SELECT id FROM stories WHERE slug='great-zimbabwe-story'), 'https://images.pexels.com/photos/131736/pexels-photo-131736.jpeg?auto=compress&cs=tinysrgb&w=800', true),

('Traditional Farming Methods', 'traditional-farming-lesson', 'Learn about the indigenous farming practices that sustained Zimbabwean communities for centuries.', 'Agriculture', 'Grade 5', 'Traditional Agriculture', 'Understand traditional farming practices and their relevance to sustainable agriculture today.', 'By the end of this lesson, learners will be able to:\n1. Describe at least three traditional farming practices\n2. Explain how intercropping works and its benefits\n3. Discuss the role of rainmaking ceremonies in the agricultural calendar\n4. Compare traditional and modern farming methods', 'beginner', 'English', '40 minutes', 'lesson', '## Introduction\nLong before modern farming, Zimbabwean communities developed sophisticated agricultural systems that worked with nature rather than against it.\n\n## Intercropping\nInstead of planting one crop per field, traditional farmers planted multiple crops together — maize, sorghum, millet, and groundnuts. This method:\n- Maximises use of space\n- Reduces pest damage (pests prefer single-crop fields)\n- Improves soil nutrition (legumes add nitrogen)\n- Provides insurance if one crop fails\n\n## Crop Rotation\nFields were rotated and rested to preserve soil fertility. A field might be used for two seasons, then left fallow to recover.\n\n## Seed Saving\nCommunities maintained diverse seed varieties, selected for taste, drought resistance, and storage quality. Seeds were stored in special containers with ash or plant extracts to protect against insects.\n\n## The Agricultural Calendar\nPlanting was guided by natural signs:\n- Flowering of certain trees indicated rain was coming\n- Bird movements signalled seasonal changes\n- Moon phases guided planting times\n\n## Rainmaking Ceremonies\nThe Mukwerera ceremony asked ancestors and Mwari for good rains. These ceremonies also synchronised planting times across communities.\n\n## Why This Matters Today\nClimate change is making rainfall unpredictable. Many traditional practices — like intercropping and seed diversity — are now recognised as climate-smart agriculture.\n\n## Activity\nInterview an elder in your community about farming practices they remember from their childhood. What has changed? What has stayed the same?', (SELECT id FROM stories WHERE slug='traditional-farming'), 'https://images.pexels.com/photos/2933243/pexels-photo-2933243.jpeg?auto=compress&cs=tinysrgb&w=800', true),

('Rivers and Landscapes of Zimbabwe', 'rivers-landscapes-lesson', 'Explore Zimbabwe''s major rivers, mountains, and natural landmarks and their cultural significance.', 'Geography', 'Grade 7', 'Physical Geography', 'Identify major geographical features of Zimbabwe and understand their cultural and economic importance.', 'By the end of this lesson, learners will be able to:\n1. Name and locate Zimbabwe''s major rivers\n2. Describe the Eastern Highlands and their characteristics\n3. Explain the cultural significance of Victoria Falls\n4. Discuss how geography shapes human activity', 'intermediate', 'English', '50 minutes', 'lesson', '## Zimbabwe''s Geography\nZimbabwe is a landlocked country in southern Africa with diverse landscapes — from high mountains to river valleys to savanna plains.\n\n## Major Rivers\n- **Zambezi River** — forms the northern border, home to Victoria Falls and Lake Kariba\n- **Limpopo River** — forms the southern border\n- **Save River** — flows through the eastern lowveld\n- **Manyame River** — flows through the central plateau\n\nRivers are not just geographical features — they are cultural ones. The Zambezi is home to the Tonga people and the spirit Nyaminyami. Rivers provide water, food, transportation, and spiritual connection.\n\n## The Eastern Highlands\nThe Eastern Highlands run along the Zimbabwe-Mozambique border. Key areas:\n- **Nyanga** — mountains, ancient terraced fields, and stone ruins\n- **Bvumba** — mist forests with unique plants and animals\n- **Chimanimani** — quartz peaks popular for hiking\n\nThe highlands receive the highest rainfall in Zimbabwe and are important for agriculture and biodiversity.\n\n## Victoria Falls\nKnown locally as Mosi-oa-Tunya ("The Smoke That Thunders"), Victoria Falls is one of the world''s largest waterfalls. It is sacred to local communities and a UNESCO World Heritage Site.\n\n## Discussion\n1. How do rivers shape where people live?\n2. Why might mountains be important for cultural practices?\n3. How does Zimbabwe''s geography affect its economy?', (SELECT id FROM stories WHERE slug='victoria-falls-story'), 'https://images.pexels.com/photos/14938680/pexels-photo-14938680.jpeg?auto=compress&cs=tinysrgb&w=800', false),

('The Mbira and Zimbabwean Music', 'mbira-music-lesson', 'Discover the mbira, one of Zimbabwe''s most important traditional instruments, and its role in Shona culture.', 'Music', 'Grade 6', 'Traditional Instruments', 'Understand the cultural significance of the mbira and its role in Shona spiritual and musical traditions.', 'By the end of this lesson, learners will be able to:\n1. Describe what a mbira is and how it produces sound\n2. Explain the role of mbira in the Bira ceremony\n3. Identify how mbira music has evolved in modern times\n4. Recognise the mbira''s importance to Zimbabwean identity', 'beginner', 'English', '35 minutes', 'lesson', '## What is a Mbira?\nThe mbira dzavadzimu is a traditional Shona instrument with 22-28 metal keys mounted on a hardwood board. It is played with both thumbs and the right index finger.\n\nThe mbira is usually placed inside a large calabash gourd (deze) that amplifies the sound. Bottle caps or shells are often attached to create a buzzing sound that is considered beautiful in Shona aesthetics.\n\n## The Bira Ceremony\nThe most important context for mbira music is the Bira — an all-night ceremony where mbira is played to call ancestors. The music creates a bridge between the living and the spirit world.\n\nDuring a Bira:\n- Musicians play from sunset to sunrise\n- A spirit medium (svikiro) may become possessed by an ancestor\n- The community seeks guidance, healing, or rain\n- The music creates a communal, meditative atmosphere\n\n## Modern Evolution\nArtists like Thomas Mapfumo adapted mbira patterns to electric guitar, creating chimurenga music. Today, young musicians are mixing mbira with jazz, electronic, and hip-hop.\n\n## Activity\nListen to a recording of mbira music. What do you hear? How does it make you feel? Try to identify the repeating patterns.', (SELECT id FROM stories WHERE slug='mbira-music'), 'https://images.pexels.com/photos/167636/pexels-photo-167636.jpeg?auto=compress&cs=tinysrgb&w=800', true),

('Resistance and Independence', 'resistance-independence-lesson', 'Learn about the spirit mediums and leaders who resisted colonisation and the path to independence.', 'History', 'Grade 7', 'Colonial Period and Independence', 'Understand the role of spirit mediums in resistance and the path to Zimbabwe''s independence.', 'By the end of this lesson, learners will be able to:\n1. Describe the role of Mbuya Nehanda in the First Chimurenga\n2. Explain the connection between spiritual authority and political resistance\n3. Outline key events leading to independence in 1980\n4. Discuss the meaning of "Chimurenga"', 'intermediate', 'English', '45 minutes', 'lesson', '## The First Chimurenga (1896-1897)\nWhen British colonisers arrived in the 1890s, they faced resistance from both Shona and Ndebele people. The uprising of 1896-97 became known as the First Chimurenga.\n\n## Mbuya Nehanda\nMbuya Nehanda Charwe Nyakasikana was a Shona spirit medium whose authority came from the spirit (mhondoro) that possessed her. She rallied communities to resist forced labour, land seizure, and taxation.\n\nHer famous words before her execution — "Mapfupa angu achamuka" ("My bones will rise") — became a prophecy that inspired the independence struggle decades later.\n\n## The Second Chimurenga\nThe armed struggle for independence in the 1960s and 1970s was called the Second Chimurenga, directly connecting to the earlier resistance. Spirit mediums played roles in this struggle as well, providing spiritual legitimacy to the fighters.\n\n## Independence\nZimbabwe gained independence on 18 April 1980. The legacy of resistance — from Mbuya Nehanda to the guerrilla fighters — is central to the nation''s founding story.\n\n## Discussion\n1. Why were spirit mediums able to unite communities for resistance?\n2. What does "Chimurenga" mean and why was it used for both struggles?\n3. How does historical memory shape national identity?', (SELECT id FROM stories WHERE slug='womens-heritage'), 'https://images.pexels.com/photos/3752854/pexels-photo-3752854.jpeg?auto=compress&cs=tinysrgb&w=800', false),

('Great Zimbabwe Revision Notes', 'great-zimbabwe-revision', 'Quick revision notes covering the key facts about Great Zimbabwe for exam preparation.', 'Heritage Studies', 'Grade 6', 'Great Zimbabwe', 'Consolidate knowledge about Great Zimbabwe for assessment.', 'Quick reference revision sheet with key facts, dates, and terms.', 'intermediate', 'English', '15 minutes', 'revision_notes', '## Key Facts\n- **Location**: Near Masvingo, southeastern Zimbabwe\n- **Period**: Built 11th–15th century CE\n- **Peak population**: Up to 18,000 people\n- **UNESCO World Heritage Site**: Designated 1986\n- **Name origin**: "Dzimba dza mabwe" = "houses of stone" in Shona\n\n## Three Main Areas\n1. **Hill Complex** — oldest section, royal residence\n2. **Great Enclosure** — largest ancient structure in sub-Saharan Africa\n3. **Valley Ruins** — residential quarters\n\n## Construction\n- Dry-stone walls (no mortar)\n- Granite blocks split from surrounding hills\n- Walls up to 11 metres high, some 5 metres thick\n\n## Trade\n- **Exports**: Gold, ivory, copper\n- **Imports**: Chinese porcelain, glass beads, cotton cloth\n- **Trade networks**: Reached as far as China, India, and the Middle East\n\n## The Zimbabwe Bird\n- Carved from soapstone\n- Found at the site\n- National symbol of modern Zimbabwe\n- Appears on the national flag and currency\n\n## Decline\n- Abandoned around 1450 CE\n- Possible causes: environmental pressure, trade route shifts, political instability\n\n## Key Terms\n- **Dzimba dza mabwe** — houses of stone\n- **Mwari** — supreme deity in Shona religion\n- **Dry-stone construction** — building without mortar\n- **Soapstone** — soft stone used for carving', (SELECT id FROM stories WHERE slug='great-zimbabwe-story'), 'https://images.pexels.com/photos/131736/pexels-photo-131736.jpeg?auto=compress&cs=tinysrgb&w=800', false)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- QUIZZES
-- ============================================================
INSERT INTO quizzes (title, slug, description, subject, grade, resource_id, story_id, passing_score) VALUES
('Great Zimbabwe Quiz', 'great-zimbabwe-quiz', 'Test your knowledge about Great Zimbabwe — the stone city that gave the nation its name.', 'Heritage Studies', 'Grade 6', (SELECT id FROM educational_resources WHERE slug='great-zimbabwe-lesson'), (SELECT id FROM stories WHERE slug='great-zimbabwe-story'), 70),
('Traditional Farming Quiz', 'traditional-farming-quiz', 'Check your understanding of traditional Zimbabwean farming practices.', 'Agriculture', 'Grade 5', (SELECT id FROM educational_resources WHERE slug='traditional-farming-lesson'), (SELECT id FROM stories WHERE slug='traditional-farming'), 70),
('Mbira Music Quiz', 'mbira-music-quiz', 'How much do you know about the mbira and its role in Zimbabwean culture?', 'Music', 'Grade 6', (SELECT id FROM educational_resources WHERE slug='mbira-music-lesson'), (SELECT id FROM stories WHERE slug='mbira-music'), 70)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- QUIZ_QUESTIONS
-- ============================================================
-- Great Zimbabwe Quiz
INSERT INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
((SELECT id FROM quizzes WHERE slug='great-zimbabwe-quiz'), 'What does the name "Zimbabwe" mean in Shona?', 'Houses of stone', 'Great mountain', 'River of gold', 'Land of elephants', 'A', '"Dzimba dza mabwe" means "houses of stone," referring to the Great Zimbabwe ruins.', 1),
((SELECT id FROM quizzes WHERE slug='great-zimbabwe-quiz'), 'During which centuries was Great Zimbabwe built?', '5th–9th century', '11th–15th century', '16th–18th century', '1st–4th century', 'B', 'Great Zimbabwe was built between the 11th and 15th centuries CE.', 2),
((SELECT id FROM quizzes WHERE slug='great-zimbabwe-quiz'), 'What construction method was used at Great Zimbabwe?', 'Mud brick', 'Cement and stone', 'Dry-stone (no mortar)', 'Wood and clay', 'C', 'The walls were built using dry-stone construction — granite blocks fitted without mortar.', 3),
((SELECT id FROM quizzes WHERE slug='great-zimbabwe-quiz'), 'Which of these items was found at Great Zimbabwe, showing trade with Asia?', 'Roman coins', 'Chinese porcelain', 'Indian swords', 'Japanese pottery', 'B', 'Chinese porcelain fragments and glass beads were found, proving trade with Asia.', 4),
((SELECT id FROM quizzes WHERE slug='great-zimbabwe-quiz'), 'What is the Zimbabwe Bird carved from?', 'Granite', 'Wood', 'Soapstone', 'Ivory', 'C', 'The Zimbabwe Bird sculptures were carved from soapstone.', 5),
((SELECT id FROM quizzes WHERE slug='great-zimbabwe-quiz'), 'Approximately how many people may have lived at Great Zimbabwe at its peak?', '1,000', '5,000', '18,000', '100,000', 'C', 'At its peak, Great Zimbabwe may have housed up to 18,000 people.', 6)
ON CONFLICT DO NOTHING;

-- Traditional Farming Quiz
INSERT INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
((SELECT id FROM quizzes WHERE slug='traditional-farming-quiz'), 'What is intercropping?', 'Planting one crop per field', 'Planting multiple crops together in the same field', 'Rotating crops each year', 'Using irrigation systems', 'B', 'Intercropping means planting multiple crops (e.g., maize, sorghum, and groundnuts) together in the same field.', 1),
((SELECT id FROM quizzes WHERE slug='traditional-farming-quiz'), 'What is the Mukwerera ceremony?', 'A harvest festival', 'A rainmaking ceremony', 'A marriage ceremony', 'A funeral rite', 'B', 'The Mukwerera is a traditional Shona rainmaking ceremony asking ancestors and Mwari for good rains.', 2),
((SELECT id FROM quizzes WHERE slug='traditional-farming-quiz'), 'Why did traditional farmers save seeds?', 'To sell them at market', 'To maintain diverse varieties adapted to local conditions', 'Because they had no other choice', 'To offer them to spirits', 'B', 'Seed saving maintained diverse varieties adapted to local conditions, selected for taste, drought resistance, and storage.', 3),
((SELECT id FROM quizzes WHERE slug='traditional-farming-quiz'), 'What natural signs guided planting times?', 'Radio broadcasts', 'Newspaper weather reports', 'Tree flowering and bird movements', 'Government announcements', 'C', 'Traditional farmers observed tree flowering, bird movements, and moon phases to guide planting.', 4),
((SELECT id FROM quizzes WHERE slug='traditional-farming-quiz'), 'Why are traditional farming practices relevant today?', 'They are not relevant anymore', 'They offer climate-resilient, sustainable approaches', 'They produce more food than modern farming', 'They are required by law', 'B', 'Many traditional practices like intercropping and seed diversity are now recognised as climate-smart agriculture.', 5)
ON CONFLICT DO NOTHING;

-- Mbira Music Quiz
INSERT INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
((SELECT id FROM quizzes WHERE slug='mbira-music-quiz'), 'How many metal keys does a mbira dzavadzimu typically have?', '5–10', '22–28', '40–50', '100+', 'B', 'The mbira dzavadzimu typically has 22 to 28 metal keys.', 1),
((SELECT id FROM quizzes WHERE slug='mbira-music-quiz'), 'What is the Bira ceremony?', 'A wedding celebration', 'An all-night ceremony to call ancestors', 'A musical competition', 'A harvest festival', 'B', 'The Bira is an all-night ceremony where mbira is played to call and communicate with ancestors.', 2),
((SELECT id FROM quizzes WHERE slug='mbira-music-quiz'), 'What gourd is used to amplify the mbira?', 'Pumpkin', 'Calabash (deze)', 'Coconut', 'Ceramic pot', 'B', 'The mbira is placed inside a large calabash gourd called the deze to amplify the sound.', 3),
((SELECT id FROM quizzes WHERE slug='mbira-music-quiz'), 'Which musician adapted mbira patterns to electric guitar?', 'Oliver Mtukudzi', 'Thomas Mapfumo', 'Brenda Fassie', 'Fela Kuti', 'B', 'Thomas Mapfumo developed chimurenga music by adapting mbira patterns to electric guitar.', 4),
((SELECT id FROM quizzes WHERE slug='mbira-music-quiz'), 'What is a svikiro?', 'A type of drum', 'A spirit medium', 'A musical scale', 'A traditional dance', 'B', 'A svikiro is a spirit medium who may become possessed by ancestors during a Bira ceremony.', 5)
ON CONFLICT DO NOTHING;

-- ============================================================
-- SUBMISSIONS
-- ============================================================
INSERT INTO submissions (title, content_type, description, contributor_name, contributor_email, community, language, province, place_name, status, image_url, consent_given, admin_notes) VALUES
('Story of the Baobab Tree at Chiredzi', 'story', 'My grandmother told me about a sacred baobab tree near our village in Chiredzi that was used as a meeting place for elders. The tree is estimated to be over 500 years old. I want to document this story for future generations.', 'Farai Mudzingwa', 'farai.m@example.com', 'Shangaan', 'Shangaan', 'Masvingo', 'Chiredzi', 'community_review', 'https://images.pexels.com/photos/1031641/pexels-photo-1031641.jpeg?auto=compress&cs=tinysrgb&w=400', true, 'AI transcription completed. Researcher reviewed and confirmed plausibility. Community review in progress.'),
('Traditional Pottery Techniques of Bikita', 'oral_history', 'An interview with Gogo Muringi about how pottery was made in Bikita district using clay from the riverbed, shaped by hand, and fired in open kilns. The interview is 25 minutes long and in chiShona.', 'Patience Nziramasanga', 'patience.n@example.com', 'Shona', 'chiShona', 'Masvingo', 'Bikita', 'ai_processed', NULL, true, 'AI processing complete — transcript and summary generated. Awaiting researcher review.')
ON CONFLICT DO NOTHING;

-- ============================================================
-- VERIFICATION_RECORDS
-- ============================================================
INSERT INTO verification_records (submission_id, stage, reviewer_name, notes, status) VALUES
((SELECT id FROM submissions WHERE title='Story of the Baobab Tree at Chiredzi' LIMIT 1), 'submitted', NULL, 'Submission received from community contributor.', 'completed'),
((SELECT id FROM submissions WHERE title='Story of the Baobab Tree at Chiredzi' LIMIT 1), 'ai_processed', 'AI System', 'Content categorised as oral_history. Topics extracted: baobab, sacred trees, community gatherings, elders. Language: Shangaan. No sensitive content detected.', 'completed'),
((SELECT id FROM submissions WHERE title='Story of the Baobab Tree at Chiredzi' LIMIT 1), 'research_review', 'Dr. Ruramisai Moyo', 'Story is plausible and consistent with known traditions about sacred trees. Recommend community review by Shangaan community members.', 'completed'),
((SELECT id FROM submissions WHERE title='Story of the Baobab Tree at Chiredzi' LIMIT 1), 'community_review', 'Chief Sengwe (pending)', 'Awaiting confirmation from community elders that this story can be shared publicly.', 'in_progress'),
((SELECT id FROM submissions WHERE title='Traditional Pottery Techniques of Bikita' LIMIT 1), 'submitted', NULL, 'Submission received.', 'completed'),
((SELECT id FROM submissions WHERE title='Traditional Pottery Techniques of Bikita' LIMIT 1), 'ai_processed', 'AI System', 'Audio transcribed (chiShona). Summary generated. Topics: pottery, clay, firing techniques, Bikita. Potential curriculum link: Grade 5 Art.', 'completed')
ON CONFLICT DO NOTHING;